#!/usr/bin/env python3
"""
Ingestion pipeline: files -> clean text -> chunks -> metadata -> Pinecone.

One reliable path, so adding documents in volume stays safe:

    extract  ->  quality gate (quarantine scans)  ->  clean OCR artifacts
             ->  Chonkie RecursiveChunker         ->  metadata + concept tags
             ->  embed -> Pinecone + SQLite

Design decisions worth keeping:

* Documents that yield too little text are QUARANTINED, never ingested. An
  image-only PDF ingested as an empty record is retrievable and useless, and
  that failure is invisible until someone wonders why answers are thin.
* Concept tags are generated by a model rather than matched against a keyword
  list, so the library surfaces connections nobody thought to enumerate.
* Framework mappings (chakra <-> step <-> Fleet's creation arc) are written
  into metadata, because no embedding finds them: the texts share no vocabulary.

Usage:
    python tools/ingest.py --inventory inventory.csv --dry-run
    python tools/ingest.py --inventory inventory.csv --limit 5
    python tools/ingest.py --inventory inventory.csv
"""

import argparse
import csv
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract import extract
from dedupe import group_and_select
from known_authors import ASCENSION_PATH, FRAMEWORK_LINKS, is_excluded

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKEND = os.path.join(REPO, "backend")

CHUNK_SIZE = 1500          # tokens; see STATUS.md for why this was settled
EMBED_BATCH = 64
UPSERT_BATCH = 50


def safe_id(filename: str, chunk_index: int) -> str:
    """
    Build a Pinecone vector id that can be fetched back.

    Ids containing spaces or "::" upsert and query fine but return nothing
    from fetch(), which makes them invisible to a backup export — a silent
    data-loss path. Restrict to ASCII word characters, dash and dot.
    """
    import re
    base = re.sub(r"[^A-Za-z0-9._-]", "_", filename)
    return f"{base}-{chunk_index}"


def load_clients():
    from dotenv import load_dotenv
    from openai import OpenAI
    from pinecone import Pinecone

    load_dotenv(os.path.join(BACKEND, ".env"), override=True)
    oa = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    pc = Pinecone(api_key=os.getenv("PINECONE_API_KEY"))
    index = pc.Index(os.getenv("PINECONE_INDEX_NAME"))
    model = os.getenv("EMBEDDING_MODEL", "text-embedding-3-large")
    return oa, index, model


def framework_metadata(text: str, collection: str, author: str):
    """
    Attach cross-tradition mappings that retrieval cannot infer.

    A Fourth Step document and a neuroplasticity paper describe one mechanism
    in two vocabularies; nothing in either text links them. The mapping is
    asserted here so agents can reason across traditions.
    """
    low = text.lower()
    meta = {}

    stages = []
    for entry in ASCENSION_PATH:
        hit = entry["chakra"].replace("_", " ") in low
        hit = hit or any(
            f"step {n}" in low or f"step-{n}" in low for n in entry["steps"]
        )
        if hit:
            stages.append(entry["stage"])
            meta.setdefault("chakras", []).append(entry["chakra"])
            meta.setdefault("steps", []).extend(str(s) for s in entry["steps"])
    if stages:
        meta["ascension_stages"] = sorted({str(s) for s in stages})

    links = FRAMEWORK_LINKS.get((author or "").lower())
    if links:
        meta["framework_links"] = links

    for key in ("chakras", "steps"):
        if key in meta:
            meta[key] = sorted(set(meta[key]))
    return meta


def concept_tags(oa, text: str):
    """
    Ask a model what a passage is ABOUT, rather than matching a fixed list.

    This is how connections nobody enumerated get surfaced. Kept to a short
    controlled shape so the values stay filterable — the opposite of the
    free-form `consciousness_level` field, which acquired ~150 unique values
    and became useless.
    """
    try:
        resp = oa.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": (
                "Read this passage and return ONLY JSON with:\n"
                '  concepts: up to 6 short lowercase concept tags\n'
                '  practice: one of meditation|inventory|prayer|breathwork|'
                'movement|study|service|none\n'
                '  evidence_base: one of clinical|traditional|experiential\n\n'
                f"Passage:\n\"\"\"{text[:1500]}\"\"\""
            )}],
            max_tokens=200, temperature=0,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        out = {}
        c = data.get("concepts")
        if isinstance(c, list):
            out["concepts"] = [str(x).lower()[:40] for x in c[:6]]
        for k in ("practice", "evidence_base"):
            v = data.get(k)
            if isinstance(v, str) and v and v != "none":
                out[k] = v.lower()[:30]
        return out
    except Exception:
        return {}


def embed_batch(oa, model, texts):
    resp = oa.embeddings.create(model=model, input=texts)
    return [d.embedding for d in resp.data]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--inventory", required=True)
    ap.add_argument("--limit", type=int)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--no-concepts", action="store_true",
                    help="skip model-generated concept tags")
    args = ap.parse_args()

    rows = [r for r in csv.DictReader(open(args.inventory))
            if not r["is_own_content"] and not is_excluded(r["path"])]
    keep, dropped = group_and_select([r["path"] for r in rows])
    by_path = {r["path"]: r for r in rows}
    docs = [by_path[p] for p in keep if p in by_path]
    if args.limit:
        docs = docs[: args.limit]

    print(f"{len(rows)} source rows -> {len(docs)} after dedup "
          f"({len(dropped)} duplicates skipped)")

    from chonkie import RecursiveChunker
    chunker = RecursiveChunker(chunk_size=CHUNK_SIZE)

    oa = index = model = None
    if not args.dry_run:
        oa, index, model = load_clients()

    quarantined, ingested, total_chunks = [], 0, 0

    for i, row in enumerate(docs, 1):
        path = row["path"]
        title = row["title"] or row["filename"]
        print(f"[{i}/{len(docs)}] {title[:60]}")

        res = extract(path)
        if not res["ok"]:
            print(f"    QUARANTINED: {res['reason']}")
            quarantined.append({"file": row["filename"], "reason": res["reason"],
                                "path": path})
            continue

        chunks = chunker(res["text"])
        total_chunks += len(chunks)
        print(f"    {res['pages']}p, {res['chars']:,} chars -> {len(chunks)} chunks")

        if args.dry_run:
            continue

        base = {
            "title": row["filename"],
            "display_title": title[:200],
            "author": row["author"] or "",
            "work": row["work"] or "",
            "doc_type": row["doc_type"] or "",
            "collection": row["collection"] or "unsorted",
            "source": "library",
            "total_chunks": len(chunks),
        }
        base.update(framework_metadata(res["text"], base["collection"],
                                       base["author"]))

        vectors = []
        for start in range(0, len(chunks), EMBED_BATCH):
            batch = chunks[start:start + EMBED_BATCH]
            texts = [c.text for c in batch]
            embeddings = embed_batch(oa, model, texts)
            for j, (chunk, emb) in enumerate(zip(batch, embeddings)):
                idx = start + j
                md = dict(base)
                md["chunk_index"] = idx
                md["text"] = chunk.text[:3000]
                if not args.no_concepts and idx == 0:
                    md.update(concept_tags(oa, chunk.text))
                md = {k: v for k, v in md.items() if v not in ("", None, [])}
                vectors.append({
                    # Vector ids must survive a round trip through fetch().
                    # Spaces and "::" do not: such vectors stay queryable but
                    # become unfetchable, so a backup silently skips them.
                    "id": safe_id(row["filename"], idx),
                    "values": emb,
                    "metadata": md,
                })

        for start in range(0, len(vectors), UPSERT_BATCH):
            index.upsert(vectors=vectors[start:start + UPSERT_BATCH])
            time.sleep(0.1)

        ingested += 1

    print(f"\n{'DRY RUN — nothing written' if args.dry_run else 'INGESTED'}")
    print(f"  documents: {ingested}/{len(docs)}   chunks: {total_chunks:,}")
    if quarantined:
        out = os.path.join(REPO, "quarantine.json")
        json.dump(quarantined, open(out, "w"), indent=2)
        print(f"  quarantined: {len(quarantined)} -> {out}")


if __name__ == "__main__":
    main()
